openapi: 3.0.3
info:
  title: Employees API
  description: |-
    This is employees API to define allowed operations on employee object
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://6433c739582420e2316b3baa.mockapi.io/v1
tags:
  - name: HRMS
    description: Everything about HRMS
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /employees/{employeeId}:
    get:
      tags:
        - HRMS
      summary: Get employee details by ID
      description: Returns a single employee
      operationId: getEmployeeById
      parameters:
        - name: employeeId
          in: path
          description: ID of employee to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Pet not found
    delete:
      tags:
          - HRMS
      summary: Delete employee  by ID
      description: Deletes employee
      operationId: deleteEmployeeById
      parameters:
        - name: employeeId
          in: path
          description: ID of employee to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
      security:
        - api_key: []
        - petstore_auth:
            - write:pets
            - read:pets
    put:
      tags:
        - HRMS
      summary: Update employee details by ID
      description: Returns a single employee
      operationId: updateEmployeeById
      parameters:
        - name: employeeId
          in: path
          description: ID of employee to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Employee data with the updated values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Pet not found
  /employees:
    post:
      summary: allow create employee
      description: Create employee
      operationId: createEmployee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
components:
  schemas:
    Employee:
      type: object
      properties:
        firstName:
          type: string
          description: Employee first name
          example: Seshi
        lastName:
          type: string
          example: A
        email:
          type: string
          format: email
        active:
          type: boolean
        skills:
          type: array
          items:
            type: string
        address:
          type: object
          properties:
            addresLine1:
              type: string
            addressLine2:
              type: string
            city:
              type: string
            pincode:
              type: integer
          required:
          - addresLine1
          - addressLine2
          - city
          - pincode
      required:
      - firstName
      - lastName
      - email
      - active
      - skills
      - address

    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header